Decouple the powerline bash setup from the pip install.

diff --git a/use_config b/use_config
--- a/use_config
+++ b/use_config
@@ -58,30 +58,36 @@ function setup_i3 {
 SETUP_POWERLINE=false
 function setup_powerline {
   if [ $SETUP_POWERLINE == true ]; then
+      PYTHON_USER_SITE=`python2 -m site --user-site`
+
+      SETUP_POWERLINE_BASH=true
       # Check if powerline was already setup
       while read -r line
       do
           if (echo "$line" | grep --quiet "powerline-daemon"); then
-              SETUP_POWERLINE=false
-              echo "Powerline is already installed"
-              echo "Restarting"
-              powerline-daemon -q --replace
-              return 0
+              SETUP_POWERLINE_BASH=false
           fi
       done < "${HOME}/.bashrc"
-
-      pip2 install powerline-status powerline-gitstatus
-      if [ $? -ne 0 ]; then
-          echo "Failed to setup powerline"
-          exit 1
+      if [ $SETUP_POWERLINE_BASH == true ]; then
+        echo "" >> ~/.bashrc
+        echo "# Powerline setup" >> ~/.bashrc
+        echo "powerline-daemon -q" >> ~/.bashrc
+        echo "POWERLINE_BASH_CONTINUATION=1" >> ~/.bashrc
+        echo "POWERLINE_BASH_SELECT=1" >> ~/.bashrc
+        echo "source ${PYTHON_USER_SITE}/powerline/bindings/bash/powerline.sh" >> ~/.bashrc
       fi
-      PYTHON_USER_SITE=`python2 -m site --user-site`
-      echo "" >> ~/.bashrc
-      echo "# Powerline setup" >> ~/.bashrc
-      echo "powerline-daemon -q" >> ~/.bashrc
-      echo "POWERLINE_BASH_CONTINUATION=1" >> ~/.bashrc
-      echo "POWERLINE_BASH_SELECT=1" >> ~/.bashrc
-      echo "source ${PYTHON_USER_SITE}/powerline/bindings/bash/powerline.sh" >> ~/.bashrc
+
+      if pip2 show --quiet powerline-status; then
+          echo "Powerline is already installed"
+          echo "Restarting"
+          powerline-daemon -q --replace
+      else
+        pip2 install powerline-status powerline-gitstatus
+        if [ $? -ne 0 ]; then
+            echo "Failed to setup powerline"
+            return 1
+        fi
+      fi
 
       POWERLINE_THEME=${PYTHON_USER_SITE}/powerline/config_files/themes/shell/default.json
       if [ ! -L ${POWERLINE_THEME} ]; then
